# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Mohammad Amin Nabian
title: Senior Software Engineer, AI - HPC, NVIDIA
email: mnabian@nvidia.com
phone: 202-304-6701
website: mnabian.github.io

# Social links
twitter_username: jekyllrb
github_username:  mnabian
instagram_username: m.a.nabian
linkedin_username: mohammad-amin-nabian-9b0b9352


# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a Senior Software Engineer specialized in AI, HPC at the NVIDIA headquarters located in Santa Clara, California. I received my PhD degree form the University of Illinois at Urbana-Champaign. My research interests include <mark>artificial intelligence</mark>, <mark>machine learning and deep learning</mark>, <mark>physics-informed neural networks</mark>, <mark>uncertainty quantification</mark>, and <mark>computational mechanics</mark>. Primarily, I am interested in developing metamodels based on deep neural networks to accelerate stochastic computations in engineering systems, with applications in reliability analysis, design optimization, Bayesian inference, and computational fluid dynamics. Currently I am a member of the [NVIDIA SimNet team](http://developer.nvidia.com/simnet). You may want to take a look at my [CV](https://www.dropbox.com/s/xlmhhi56tzgn809/CV.pdf?dl=0), my [Google Scholar profile](https://scholar.google.com/citations?user=NVXDhJAAAAAJ&hl=en), and my [Researchgate profile](https://www.researchgate.net/profile/Mohammad_Amin_Nabian).

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Education Section
# educaton_title: Education #(Use this to override about education section title)

# Publications Section
# Publications_title: Publications

# More Section
more_title: Honors & Awards
more_content: | 
  - Cited in the List of Teachers Ranked as Excellent by the Center for Teaching Excellence, University of Illinois at Urbana-Champaign, [Spring 2018](https://citl.illinois.edu/docs/default-source/teachers-ranked-as-excellent/tre-2018-spring.pdf) and [Fall 2018](https://citl.illinois.edu/docs/default-source/teachers-ranked-as-excellent/tre-2018-fall.pdf) (two time winner).
  - Winner of the [second prize](https://www.dropbox.com/s/515i0r1fzn3lis7/RAS.jpg?dl=0) in the 2018 INFORMS Railway Application Section problem solving competition. [Full Story](https://cee.illinois.edu/news/cee-team-places-second-international-competition)
  - Natural Hazards Engineering Research Infrastructure (NHERI) Travel Award, for Researchers Workshop: Advanced Simulation for Natural Hazards Mitigation, Lehigh University, Bethlehem, PA (2017).
  - Natural Hazards Engineering Research Infrastructure (NHERI) Travel Award, for NSF NHERI Wall of Wind (WOW) Experimental Facility User Workshop, Florida International University, Miami, FL (2017).
  - Distinguished Graduate Teaching Assistantship Award, University of Illinois at Urbana-Champaign (2016).
  - Graduate Research Assistantship Award, University of Illinois at Urbana-Champaign, (2015-Present).
  - Graduate Fellowship Award, University of Illinois at Urbana-Champaign, (2015-2016).
  - American Society of Mechanical Engineers (ASME) Award, for the ASME 2015 International Mechanical Engineering Congress and Exposition, Houston, TX (2015).
  - American Society of Mechanical Engineers (ASME) Award of Excellence for Outstanding Paper, ASME-JSME-KSME Joint Fluids Engineering Conference, Seoul, Korea (2014). [Full Story](https://community.asme.org/fluids_engineering_division/b/weblog/archive/2016/06/21/fluids-engineering-2016-spring-newsletter.aspx)
  - Named ASME Fluids Engineering Division Graduate Scholar of the Year, [Award](https://www.dropbox.com/s/bgq15u162igx1yw/ASME%20Certificate%2C%20Mohammad%20Amin%20Nabian.pdf?dl=0) Received During the ASME 2014 4th Joint US-European Fluids Engineering Division, Chicago, IL (2014). [Full Story](https://community.asme.org/fluids_engineering_division/b/weblog/archive/2015/06/11/fluids-engineering-newsletter-spring-2015.aspx)
  - Graduate Research Assistantship Award, The George Washington University, (2013-2015).
  - Graduate Teaching Assistantship Award, The George Washington University, (2013-2015).
  - Recipient of the National Organization for Educational Testing (NOET) Certificate of Recognition for Exceptional Talent (for ranking 342 among more than 400,000 participants in the nationwide university entrance exam), (2009).

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
