# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Mohammad Amin Nabian
title: PhD Candidate, University of Illinois at Urbana Champaign
email: mnabia2@illinois.edu
phone: 202-304-6701
website: mnabian.github.io

# Social links
twitter_username: jekyllrb
github_username:  mnabian
instagram_username: mohnabian
linkedin_username: mohammad-amin-nabian-9b0b9352


# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a PhD Candidate in Sustainable and Resilient Infrastructure Systems program in the Department of Civil and Environmental Engineering at the University of Illinois at Urbana-Champaign. My research interests include <mark>infrastructure engineering</mark>, <mark>machine learning and deep learning</mark>, <mark>uncertainty quantification</mark>, <mark>computational statistics</mark>, and <mark>computational fluid dynamics</mark>. Primarily, I am interested in developing metamodels based on deep neural networks to accelerate stochastic computations in engineering systems, with applications in reliability analysis, design optimization, Bayesian inference, and computational fluid dynamics. Currently I am a member of the [Uncertainty Quantification group](http://publish.illinois.edu/meidani/). You may like to take a look at my [CV](https://www.dropbox.com/s/2rcq4sbiw7szomy/CV.pdf?dl=0), my [Google Scholar profile](https://scholar.google.com/citations?user=NVXDhJAAAAAJ&hl=en), and my [Researchgate profile](https://www.researchgate.net/profile/Mohammad_Amin_Nabian).

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Education Section
# educaton_title: Education #(Use this to override about education section title)

# Experience Section
# experience_title: Publications & Presentations

# More Section
more_title: Publications #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  - Nabian, M.A., and Meidani, H., Deep Learning for Accelerated Seismic Reliability Analysis of Transportation Networks,Computer-Aided Civil and Infrastructure Engineering, 33 (6), 443-458 (2018).
  - Nabian, M.A., and Meidani, H., A Deep Learning Solution Approach for High-Dimensional Random Differential Equations, Probabilistic Engineering Mechanics (Under Review).
  - Nabian, M.A., and Meidani, H., Physics-Informed Regularization of Deep Neural Networks, Journal of Computing and Information Science in Engineering (Under Review).
  - Nabian, M.A., Alemazkoor, N., and Meidani, H., Predicting Near-Term Train Schedule Performance and Delay Using Bi-Level Random Forests, Transportation Research RecordsIn Press.
  - Nabian, M.A., and Farhadi, L., A Mesh-Free Particle Method for Simulation of Granular Flows and Sediment Transport, Journal of Hydraulic Engineering, 143 (4), 04016102 (2016).
  - Nabian, M.A., and Meidani, H., Accelerating Stochastic Assessment of Post-Earthquake Transportation Network Connectivity via Machine-Learning-Based Surrogates,Transportation Research Board, (2018).
  - Nabian, M.A., and Meidani, H., Uncertainty Quantification and PCA-Based Dimension Reduction for Parallel Monte Carlo Analysis of Infrastructure System Reliability,Transportation Research Board (2017).
  - Nabian,  M.A.,  and Farhadi,  L.,  Numerical Simulation of Solitary Wave Using the Fully Lagrangian Method of Moving Particle Semi Implicit. In ASME 2014 4th Joint US-European Fluids Engineering Division, American Society of Mechanical Engineers (2014)(Awarded Paper).
  - Nabian, M.A., and Farhadi, L., Stable Moving Particle Semi Implicit Method for Modeling Waves Generated by Submarine Landslides. In Proceedings of the ASME 2014 International Mechanical Engineering Congress andExposition, American Society of Mechanical Engineers (2014).
  - Nabian, M.A., and Farhadi, L., Simulating Water Waves Generated by Underwater Landslide with MPS and WC-MPS, In Proceedings of the 11th International Conference on Hydrodynamics (ICHD), 859-866.  ISBN 978-981-09-2175-0 (2014).
  - Nabian, M.A., An efficient mesh-free particle method for modeling of free surface and multiphase flows, M.Sc. Thesis, The George Washington University (2015).

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
