# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Mohammad Amin Nabian
title: PhD Candidate, University of Illinois at Urbana Champaign
email: mnabia2@illinois.edu
phone: 202-304-6701
website: mnabian.github.io

# Social links
twitter_username: jekyllrb
github_username:  mnabian
instagram_username: mohnabian
linkedin_username: mohammad-amin-nabian-9b0b9352


# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a PhD Candidate in Sustainable and Resilient Infrastructure Systems program in the Department of Civil and Environmental Engineering at the University of Illinois at Urbana-Champaign. My research interests include <mark>infrastructure engineering</mark>, <mark>machine learning and deep learning</mark>, <mark>uncertainty quantification</mark>, <mark>computational statistics</mark>, and <mark>computational fluid dynamics</mark>. Primarily, I am interested in developing metamodels based on deep neural networks to accelerate stochastic computations in engineering systems, with applications in reliability analysis, design optimization, Bayesian inference, and computational fluid dynamics. Currently I am a member of the [Uncertainty Quantification group](http://publish.illinois.edu/meidani/).

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Education Section
# educaton_title: Education #(Use this to override about education section title)

# More Section
more_title: Publications #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  Nabian, M.A., and Meidani, H., Deep Learning for Accelerated Seismic Reliability Analysis of TransportationNetworks,Computer-Aided Civil and Infrastructure Engineering, 33 (6), 443-458 (2018).<br />Nabian, M.A., and Meidani, H., A Deep Learning Solution Approach for High-Dimensional Random DifferentialEquations, Probabilistic Engineering Mechanics (Under Review).<br />Nabian, M.A., and Meidani, H., Physics-Informed Regularization of Deep Neural Networks, Journal of Computing and Information Science in Engineering (Under Review).<br />Nabian, M.A., Alemazkoor, N., and Meidani, H., Predicting Near-Term Train Schedule Performance and DelayUsing Bi-Level Random Forests, Transportation Research RecordsIn Press.<br />Nabian, M.A., and Farhadi, L., A Mesh-Free Particle Method for Simulation of Granular Flows and SedimentTransport, Journal of Hydraulic Engineering, 143 (4), 04016102 (2016).

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
